name: conditional_wrapper
description: A widget that allows you to conditionally wrap a child
repository: https://github.com/ThinkDigitalSoftware/conditional_wrapper
issue_tracker: https://github.com/ThinkDigitalSoftware/conditional_wrapper/issues
homepage: https://github.com/ThinkDigitalSoftware/conditional_wrapper
version: 2.0.0

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
